version: "3.8"

services:
  # Algorand MCP Server
  mcp-server:
    build:
      context: ./algorand-mcp
      dockerfile: Dockerfile
    image: algorand-mcp:testnet
    container_name: algorand-mcp-testnet
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - ALGORAND_NETWORK=testnet
      - ALGORAND_NODE_URL=https://testnet-api.algonode.cloud
      - ALGORAND_INDEXER_URL=https://testnet-idx.algonode.cloud
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:4000/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.algorand.service=mcp"
      - "com.algorand.version=0.1.0"
      - "com.algorand.blockchain=algorand"
      - "com.algorand.network=testnet"

  # Backend API with MCP Integration
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: microlending-backend:latest
    container_name: microlending-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MCP_SERVER_URL=http://mcp-server:4000
      - ALGORAND_NETWORK=testnet
    depends_on:
      mcp-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3001/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.algorand.service=backend"
      - "com.algorand.version=1.0.0"

  # Frontend React App
  frontend:
    build:
      context: ./projects/algorand-frontend
      dockerfile: Dockerfile
    image: microlending-frontend:latest
    container_name: microlending-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_ALGOD_NETWORK=testnet
      - VITE_ALGOD_SERVER=https://testnet-api.algonode.cloud
      - VITE_ALGOD_PORT=443
      - VITE_ALGOD_TOKEN=
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "com.algorand.service=frontend"
      - "com.algorand.version=1.0.0"

networks:
  default:
    name: microlending-network
    driver: bridge
